title: The Docs (devsectools.com)
url: https://docs.devsectools.com
logo: "/assets/logo-grey.svg"

remote_theme: pmarsceill/just-the-docs
color_scheme: dark

aux_links:
  "Back to www.devsectools.com":
    - "https://www.devsectools.com"

plugins:
  - jekyll-seo-tag
ga_tracking: G-2M7CBGKQV8

gh_edit_link: true
gh_edit_link_text: "Corrections? Edit this page on GitHub!"
gh_edit_repository: "https://github.com/DevSecTools/DevSecTools.Docs"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"